---

- name: install required packages
  apt:
    name: "{{ required_packages }}"
    state: latest
    dpkg_options: 'force-confnew,force-confdef'
    autoclean: yes
    autoremove: yes
    update_cache: yes
    cache_valid_time: 3600

- name: install required python packages
  pip:
    name: "{{ required_python_packages }}"
    extra_args: --upgrade
    executable: pip3

...
